ALTER TABLE similar_songs MODIFY COLUMN similar_artist VARCHAR(750);
ALTER TABLE similar_songs MODIFY COLUMN similar_song VARCHAR(255);
ALTER TABLE songs MODIFY COLUMN artist VARCHAR(700);
ALTER TABLE songs MODIFY COLUMN lyrics LONGTEXT;
ALTER TABLE songs MODIFY COLUMN genre VARCHAR(700);
